spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Project04;encrypt=false;trustServerCertificate=true;characterEncoding=UTF-8
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          charset: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 36000

google:
  cloud:
    bucket-name: ${GOOGLE_BUCKET_NAME}
    credential-path: ${GOOGLE_CREDENTIAL_PATH}
server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
